const mutation={
    forcedata_state(state,payload){
        state.Cforcedata=payload;
    },
    forcelegend_state(state,payload){
        state.forcelegend=payload;
    },
    forceSvg_state(state,payload){
        state.forceSvg=payload;
    },
    forceColorScale_state(state,payload){
        state.forceColorScale=payload;
    },
    forceedgescale_state(state,payload){
        state.forceedgescale=payload;
    },
    CaClickdate_state(state,payload){
        state.CaClickdate=payload;
    },
    STspend_state(state,payload){
        state.STspend=payload;
    },
    professionSpend_state(state,payload){
        state.professionSpend=payload;
    },
    Allflow_state(state,payload){
        state.Allflow=payload;
    }
}
export default mutation;